import { jsPDF } from "jspdf";
import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";

const sections = [
  {
    title: "1. Getting Started",
    content: `Open the Score Entry app on your phone or computer. No login is required for basic score entry. You will see two tabs: "Search Games" and "Enter Score".`
  },
  {
    title: "2. Searching for Your Game",
    content: `Tap the "Search Games" tab. Type your first name (or last name) in the search box and tap the search button (or press Enter). A list of your scheduled games will appear. Games that have already been scored will show a green "✓ Scored" badge along with the round scores. Games not yet scored will show "Click to enter scores →".`
  },
  {
    title: "3. Entering Scores",
    content: `Tap on an unscored game in the search results. You will be taken to the "Enter Score" tab with your game pre-filled. Enter the scores for each round. The app will highlight any invalid scores in red — make sure scores follow the competition rules. Once all scores are valid, tap "Submit Scores". A confirmation message will appear when the scores are saved successfully.`
  },
  {
    title: "4. Manual Score Entry",
    content: `If you prefer, tap the "Enter Score" tab directly. Enter your Net number and Game number, then tap "Find Game" to load the team details. Then fill in the round scores and submit.`
  },
  {
    title: "5. Viewing Results",
    content: `From the home screen, tap "View Results Dashboard" to see all scores entered today. Each card shows the teams, round-by-round scores, and final totals.`
  },
  {
    title: "6. Leaderboard",
    content: `Tap "League Leaderboard" from the home screen to view the standings. Select a group from the dropdown to see player rankings including wins, losses, games played, and ladder points. You can also search for a specific player to see their match history and performance charts.`
  },
  {
    title: "7. Tips",
    content: `• Always search by your own name to find your games quickly.\n• If your game does not appear, check with the desk — the schedule may not be loaded yet.\n• Scores can only be submitted once per game. If there is an error, contact the desk.\n• The app works on any phone or computer — no app download required.`
  }
];

export default function UserManual() {
  const handleDownloadPDF = () => {
    const doc = new jsPDF({ unit: "mm", format: "a4" });
    const pageW = doc.internal.pageSize.getWidth();
    const margin = 20;
    const maxW = pageW - margin * 2;
    let y = 20;

    // Title
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text("Score Entry App — User Manual", margin, y);
    y += 8;
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100);
    doc.text("Visy Badminton League", margin, y);
    doc.setTextColor(0);
    y += 10;

    // Divider
    doc.setDrawColor(200);
    doc.line(margin, y, pageW - margin, y);
    y += 8;

    sections.forEach((sec) => {
      // Check if we need a new page
      if (y > 260) { doc.addPage(); y = 20; }

      doc.setFontSize(13);
      doc.setFont("helvetica", "bold");
      doc.text(sec.title, margin, y);
      y += 6;

      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      const lines = doc.splitTextToSize(sec.content, maxW);
      lines.forEach((line) => {
        if (y > 270) { doc.addPage(); y = 20; }
        doc.text(line, margin, y);
        y += 6;
      });
      y += 4;
    });

    // Footer
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text("Generated by Visy Score Entry App", margin, 287);

    doc.save("visy-score-entry-user-manual.pdf");
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 to-slate-700 p-6">
      <div className="max-w-2xl mx-auto bg-white rounded-2xl shadow-2xl overflow-hidden">
        <div className="bg-slate-800 text-white px-8 py-6 flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold">User Manual</h1>
            <p className="text-slate-300 text-sm mt-1">Visy Score Entry App</p>
          </div>
          <Button onClick={handleDownloadPDF} className="gap-2 bg-white text-slate-800 hover:bg-slate-100">
            <Download className="w-4 h-4" /> Download PDF
          </Button>
        </div>

        <div className="px-8 py-6 space-y-6">
          {sections.map((sec, i) => (
            <div key={i}>
              <h2 className="text-lg font-semibold text-slate-800 mb-2">{sec.title}</h2>
              <p className="text-slate-600 text-sm leading-relaxed whitespace-pre-line">{sec.content}</p>
            </div>
          ))}
        </div>

        <div className="bg-slate-50 px-8 py-4 text-center">
          <Button onClick={handleDownloadPDF} className="gap-2">
            <Download className="w-4 h-4" /> Download PDF
          </Button>
        </div>
      </div>
    </div>
  );
}